#!/bin/sh

ans=$(zenity —list —title "Make your choice" > —width=100 —height=250 —column "Choice" > Logout Suspend Reboot Poweroff);
echo $ans
case $ans in
'Logout')
  echo "logout"
  killall awesome && killall fcitx
;;
'Reboot')
  echo "reboot"
  sudo shutdown -r now
;;
'Poweroff')
  echo "poweroff"
  sudo shutdown -h now
;;
'Suspend')
  echo "suspend"
  sudo pm-suspend
;;
esac
